### ISSUE TITLE
fizzbuzz.js Code Consolidation

### ISSUE THREAD

**Issue by keawade** [calebwr/webtech#1]
Your current implementation of the for loop in `fizzbuzz.js` will work as it is but can be consolidated by initializing your `i` variable inside the `for` statement itself.

`for(var i = 1; i < 101; i++) {`

This is mostly just a stylistic thing but is also slightly more efficient.

[MDN "for" Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for#Examples)

**Comment by barberboy** [comment]
Caleb, did you try running FizzBuzz.js after this change? It's broken now with a syntax error.
